<a href="https://colab.research.google.com/github/trong-khanh-1109/CS116.M12.KHCL/blob/main/Tutorial_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Creating Numpy Arrays from Python lists

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
[3.14, 4, 2, 3] # Dạng python list có thể cho phép chứa những giá trị không cùng kiểu dữ liệu

[3.14, 4, 2, 3]

In [4]:
np.array([3.14, 4, 2, 3]) # Dạng numpy array sẽ tự động chuyển về cùng 1 kiểu dữ liệu

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
np.array([1, 2, 3, 4], dtype="float32") # Dạng numpy array cho phép định dạng kiểu dữ liệu cho giá trị bằng hàm dtype (Lợi hơn dạng python list)

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1, 2, 3, 4])

In [8]:
type(a1) # Cho ra kiểu của biến a1

numpy.ndarray

In [9]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]]) # Mảng 2 chiều

In [10]:
type(a2)

numpy.ndarray

In [12]:
a2.shape # In ra kích thước a2 (2 dòng 3 cột)

(2, 3)

In [13]:
a2.ndim # Chiều của biến a2

2

In [14]:
a2.dtype # Kiểu dữ liệu của a2

dtype('int64')

In [15]:
a2.size # Số lượng phần tử trong a2

6

#Creating Numpy Arrays from Scratch: Tạo numpy array bằng các hàm có sẵn 

###zeros, ones, full, arange, linspace

In [21]:
np.zeros((2, 4), dtype = "int64")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones((3, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.arange(0, 20, 2) # Tạo ra array có giá trị từ 0 - 20 với bước nhảy 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.full((3, 5), 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [25]:
np.linspace(0, 1, 5) # Tạo ra 5 phần bằng nhau trong đoạn 0 - 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

###Random

In [29]:
# Seed for preproducibility
np.random.seed(0) # Thêm này để các giá trị random ở các nơi khác sẽ luôn giống với mình

np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [33]:
np.random.rand(4, 4) # Giống random nhưng khác cách nhập size

array([[0.99529957, 0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232, 0.31720174],
       [0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347]])

In [31]:
np.random.normal(0 , 1, (3, 3))

array([[-0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252]])

In [32]:
np.random.randint(0, 10, (4, 5)) # Tạo ra numpy array với các số từ 0 - 9, không có 10

array([[8, 1, 1, 7, 9],
       [9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4],
       [4, 6, 4, 4, 3]])

# Array Indexing and Slicing: Truy cập vào các phần tử trong array

###One-dimentional subarrray(Mảng 1 chiều)

In [43]:
x1 = np.random.randint(20, size = 6)

In [44]:
x1

array([14,  9,  1,  4, 10, 11])

In [45]:
x1[4], x1[0], x1[-1]

(10, 14, 11)

###Multi-dimentional arrray(Mảng 1 chiều)

In [48]:
x2 = np.random.randint(20, size = (3, 4))

In [49]:
x2

array([[ 8, 11,  2, 19],
       [16,  0,  0,  6],
       [19, 14, 10, 19]])

In [50]:
x2[0, 0], x2[0][0]

(8, 8)

###Slicing : Cắt đoạn array


>X[start:stop:step]

In [46]:
x1[0:3]

array([14,  9,  1])

In [52]:
x2[:2,:3]

array([[ 8, 11,  2],
       [16,  0,  0]])

# Reshaping of Array and Transpose

In [55]:
grid = np.arange(1, 10)
grid.shape

(9,)

In [57]:
grid.reshape((3, 3)) # Đang ở kích thước 9x1 đưa về 3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
X = np.array([1, 2, 3])
X.shape

(3,)

In [60]:
X.reshape((1, 3)).shape

(1, 3)

In [62]:
x = np.array([[1., 2.], [3., 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [63]:
x.T # Chuyển vị

array([[1., 3.],
       [2., 4.]])

# Array Concatenation and Splitting

In [65]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [66]:
np.concatenate((x, y)) # Nối 2 mảng

array([1, 2, 3, 3, 2, 1])

In [67]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]]) 
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.concatenate((grid, grid)) # Mặc định axis = 0 (Nối vào row)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.concatenate((grid, grid), axis = 1) # Nối vào từng col

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [70]:
#vstack
x = np.array([1, 2, 3])

grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [71]:
np.vstack((x, grid)) # Nối theo row

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [72]:
y = np.array([[99],
              [98]])

In [73]:
np.hstack((y, grid)) # Nối theo col

array([[99,  9,  8,  7],
       [98,  6,  5,  4]])

###Splitting


In [75]:
x = np.array([1, 2, 3, 99, 69, 3, 2, 1])

In [81]:
x1, x2, x3 = np.split(x, (3, 5))

#Broadcasting and Vectorized operations

In [105]:
a = np.arange(0,3)

In [106]:
a + 5

array([5, 6, 7])

In [87]:
b = np.ones((3, 3))

In [88]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
a + b # Tự động thêm các giá trị cho a để có kích thước bằng với b để thực hiện + (Các giá trị đó đều là của a)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [101]:
c = np.arange(3).reshape((3, 1))
c

array([[0],
       [1],
       [2]])

In [107]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Ứng dụng numpy trong xác suất thống kê

In [109]:
dog_height = [600, 470, 170, 430, 300]
dog_height= np.array(dog_height)

np.std(dog_height) # Độ lệch chuẩn

147.32277488562318

In [110]:
np.var(dog_height) # Phương sai

21704.0

In [111]:
np.sqrt(np.var(dog_height)) # Cách tính thứ 2 của độ lệnh chuẩn

147.32277488562318

# Sorting array

>np.sort: Được thực hiện dựa trên giải thuật quicksort

In [113]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
np.argsort(x) # Lấy ra các index của giá trị sau khi đã sort

# Sorting along rows or columns : Sort mảng đa chiều

In [115]:
np.random.seed(42)

MatA = np.random.randint(0, 10, size = (4, 6))

In [116]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [117]:
np.sort(MatA, axis = 0) # Sắp xếp theo cột

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [118]:
np.sort(MatA, axis = 1) # Sắp xếp theo hàng

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

#Linear Algebra(Đại số tuyến tính)

In [120]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [121]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [122]:
# Nhân 2 ma trận
A.dot(B) #Cách 1

array([[20, 14],
       [56, 41],
       [92, 68]])

In [123]:
np.dot(A, B) #Cách 2

array([[20, 14],
       [56, 41],
       [92, 68]])

In [124]:
A @ B #Cách 3

array([[20, 14],
       [56, 41],
       [92, 68]])

In [125]:
B.T #(2, 3)

array([[6, 4, 2],
       [5, 3, 1]])

In [126]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

###Dot product example (Ví dụ về tích vô hướng 2 ma trận)

In [127]:
np.random.seed(0)

sale_amounts = np.random.randint(0, 20, size=(5, 3))

In [130]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [131]:
# Create weekly_sales DataFrame
import pandas as pd

weekly_sales = pd.DataFrame(sale_amounts, index = ["Mon", "Tues", "wed", "Thurs", "Fri"],
                                           columns=["Almond butter", "Peanut Butter", "Cashew Butter"])
weekly_sales


Almond butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [133]:
# Create price array
prices = np.array([10,8,12]) # Giá các hủ butter
prices.shape # Lúc đầu 3 hàng 1 cột nên lúc sau phải reshape lại

(3,)

In [134]:
# Create butter_prices DF
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns=["Almond butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [140]:
butter_prices.shape, weekly_sales.T.shape # Phải chuyển vị weekly_sales mới nhân được

((1, 3), (3, 5))

In [143]:
total_prices = weekly_sales.dot(butter_prices.T) # Nhân 2 ma trận để tính tổng giá trị bán được 1 ngày
total_prices

Price
Mon      240
Tues     138
wed      458
Thurs    232
Fri      142

In [144]:
weekly_sales["Total"] = total_prices # Thêm cột mới cho weekly_sales
weekly_sales

Almond butter  Peanut Butter  Cashew Butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142